// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYpP1Y--O9jUvaA32PipQVja3SQwQNFpg',
    appId: '1:872759243030:web:9840937ab8633f21b0e037',
    messagingSenderId: '872759243030',
    projectId: 'math-homework-ai',
    authDomain: 'math-homework-ai.firebaseapp.com',
    storageBucket: 'math-homework-ai.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBw7zGKWfORxEYpaT8RZ89QYpYbA90UK5M',
    appId: '1:872759243030:android:bfec95c28e14fd2cb0e037',
    messagingSenderId: '872759243030',
    projectId: 'math-homework-ai',
    storageBucket: 'math-homework-ai.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPQxpMb8EaLvX0BHlaM8DhM_e5OzZTOFk',
    appId: '1:872759243030:ios:7dff6c555db9e7a2b0e037',
    messagingSenderId: '872759243030',
    projectId: 'math-homework-ai',
    storageBucket: 'math-homework-ai.firebasestorage.app',
    iosBundleId: 'com.jeankpoti.mathai.mathAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCPQxpMb8EaLvX0BHlaM8DhM_e5OzZTOFk',
    appId: '1:872759243030:ios:7dff6c555db9e7a2b0e037',
    messagingSenderId: '872759243030',
    projectId: 'math-homework-ai',
    storageBucket: 'math-homework-ai.firebasestorage.app',
    iosBundleId: 'com.jeankpoti.mathai.mathAi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAYpP1Y--O9jUvaA32PipQVja3SQwQNFpg',
    appId: '1:872759243030:web:acb6a98b69734fa6b0e037',
    messagingSenderId: '872759243030',
    projectId: 'math-homework-ai',
    authDomain: 'math-homework-ai.firebaseapp.com',
    storageBucket: 'math-homework-ai.firebasestorage.app',
  );
}
